name: QLCC-FE Deployment

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: 22
          script: |
            cd /home/atus/qlcc_php/qlcc_fe/QLCC_FE/ql_chungcu
            
            git fetch origin
            git checkout main
            git pull origin main
            
            docker stop qlcc_fe || true
            docker rm qlcc_fe || true
            
            docker rmi raicacon/qlcc-fe:latest || true

            cd /home/atus/qlcc_php/deploy
            docker compose -f docker-compose-qlcc-php.yml build qlcc-frontend
            docker compose up -d qlcc-frontend
          
            docker ps
